name: Deploy playground to github pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - uses: actions/setup-node@v2
      - run: cd playground
      - run: npm i
      - run: npm run build
      - run: npm run export
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: out